### ISSUE TITLE
Suggestion: Let the bot read and store Dota MMR of linked players

### ISSUE THREAD

**Issue by Shurugaz** [MeLlamoPablo/schedulebot#11]
So users can see if the event is worth joining or if they'll struggle competing.

For example:
Confirmed for the event:
-Edward (3100 MMR)
-Frank (120 MMR)

**Comment by MeLlamoPablo** [comment]
I'll look into it, thanks for the suggestion.

**Comment by MeLlamoPablo** [comment]
Hi! As you can see in 3749e1e, this is currently being worked on. However, using the Dota game coordinator is unreliable, and difficult; I haven't been able to get it right. Apparently the bot needs to be friends with the user, which isn't ideal given how ScheduleBot works.

Instead, we'll be fetching the data from [OpenDota](http://opendota.com/), which is more reliable. The drawback is that players need to opt-in for that service, so not everyone would have their MMR displayed.

A potential solution is, if the player's MMR is not exposed on OpenDota, the bot could send the user a DM recommending them to register there.

On more serious competitive environements like tournaments, displaying MMR could be enforced, rejecting anyone who hasn't signed up on OpenDota.

What do you think?

**Comment by Shurugaz** [comment]
I think the OpenDota solution is a good one. In less competitive environments I can see some players refusing though.
Maybe there could be an  option for players to update their MMR manually with a command, like '@schedulebot set-mmr 4321'.
This would be a lot easier to implement. Players could ofcourse enter a false MMR, but after 1 game it should be pretty clear to others if said person is a fraud or not.

**Comment by MeLlamoPablo** [comment]
That seems like over complicating the issue though. In non competitive environments, are you really gonna complain about people not displaying their MMR? If you're curious about the MMR of players who aren't displyaing it, you could just ask them. After all, players should be able to hide their MMR if they're not in a league who enforces displaying it.

I think that the solution would be having three options in the `config.js`: one for enabling MMR fetching, another for enforcing displaying it, and another for letting users hide it.

**Comment by MeLlamoPablo** [comment]
This has been implemented on 35c3bfd. Thanks for the suggestion!
