### ISSUE TITLE
Suggestion: remove pinned message after inhouse/event is over.

### ISSUE THREAD

**Issue by Shurugaz** [MeLlamoPablo/schedulebot#12]
Currently when I manually unpin the message, the bot will just pin it again, the only solution atm is to remove the event itself to remove the pinned message.

**Comment by MeLlamoPablo** [comment]
The original intended behaviour was that events should be manually removed after a game. This can be easily change though.

**Comment by Shurugaz** [comment]
Ok, I see. I just thought it would be interesting to see who participated and when, but it's not that important.

**Comment by MeLlamoPablo** [comment]
Yeah but the issue is still valid, I think it's important to provide flexibility for different use manners.
