### ISSUE TITLE
Bot will always think someone left the lobby and aborts the lobby autostart

### ISSUE THREAD

**Issue by Shurugaz** [MeLlamoPablo/schedulebot#18]
[DotaClientX.js](https://github.com/MeLlamoPablo/schedulebot/blob/heroku-dota/lib/modules/dotahandler/DotaClientX.js#L253)

I think `self.enoughPeople` should be `self.currentLobby.enoughPeople`

**Comment by MeLlamoPablo** [comment]
This has been fixed on v1.2.2. Thanks for the report, good catch.
