### ISSUE TITLE
Single version

### ISSUE THREAD

**Issue by lukescott** [MeLlamoPablo/schedulebot#27]
Would it be possible to combine the dota and standard editions into a single version?

A couple of different methods come to mind:

1. Dota-specific commands could be prefixed with "dota ".

2. When creating an event specify the game `@ScheduleBot create dota "My Custom Event" "01/01/2016 15:00"`

You could allow for other games down the road. With either of these methods you could turn on/off specific games.

**Comment by MeLlamoPablo** [comment]
Seems pretty unnecessary to me with the bot as it is now, however it would be a good idea to refactor it like that if we were to add more game-specific functionality to it (Like overwatch integration and whatnot. I don't really know what can be done with the overwatch API in this case, but you get the picture).

The way I imagine it however is with different plugins: i.e you donwload "schedulebot" for the basic functionality, and a hypothetic "schedulebot-dota" plugin with the dota functionality.

However, is there any need for any of that right now? The dota version is the basic version with dota features. Either you want the dota features and download the dota version, or you don't and downlad the standard version. If you wish to create events for different games, couldn't you just do `@ScheduleBot create "DOTA - Inhouse" "01/01/2016 15:00" / @ScheduleBot add-inhouse 1` for a dota game, and `@ScheduleBot create "Overwatch - Scrim" "01/01/2016 15:00"`? If you don't add an inhouse to an event, it essentialy becomes a "vanilla" event, as in "an event from the standard version".

**Comment by lukescott** [comment]
If you can use the dota version now, why a separate dota branch? A plugin architecture would be nice, but wouldn't the quickest win be a config option? That way one branch is maintained instead of three - dota, master, and heroku. Currently dota points you to master, which points you to heroku if you want that, but dota has one-click install.

A plugin architecture would be nice. Assuming you have a clan that plays more than one game, wouldn't each set of commands need a seam of some sort? If I had a clan that played Dota and Overwatch, but some members only played one of those, could there be confusion as to which commands are relevant to them?

Perhaps you could do something like:

`@ScheduleBot create overwatch 01/01/2016 15:00 "OVERWATCH - Scrim" 6 1500-2500`

This would create an Overwatch event w/ 6 players and require SR of 1500-2500.

**Comment by MeLlamoPablo** [comment]
> Currently dota points you to master, which points you to heroku if you want that, but dota has one-click install.

I'm not currently mantaining the master branch as I've focused all my effort to dota features and I don't really have the time right now to work on it.

> Assuming you have a clan that plays more than one game, wouldn't each set of commands need a seam of some sort?

You're right, there should be a way to differentiate games. But that would only be neccessary if we were to add a second game, so that dota and other game's features don't get mixed. However, my point is that for now, it's not needed.

**Comment by MeLlamoPablo** [comment]
I'm closing this issue. Please continue the discussion in #29 if you wish.
