### ISSUE TITLE
Dota login error

### ISSUE THREAD

**Issue by mcarmody** [MeLlamoPablo/schedulebot#4]
Error: Incorrect login details were provided.

Getting this right after the line in the app log (on Heroku):
[STEAM] Successfully logged in!
[DOTA] Running!

Hosted with Heroku, re-ran the setup and setup-steam commands to make sure I got the details right.  Steam says it's logging in correctly... so I'm lost.

**Comment by MeLlamoPablo** [comment]
That seems odd. Can you copy and paste the full log that starts with `[INFO] Loading ScheduleBot... Please wait`, with their corresponding time? Also, are you using Steam Guard?

**Comment by mcarmody** [comment]
I'm not running with Steam Guard, but here's the whole log:

> 2017-01-03T00:44:56.743749+00:00 app[bot.1]: [INFO] Loading ScheduleBot... Please wait
> 2017-01-03T00:44:56.935283+00:00 app[bot.1]: [STEAM] Sentry file doesn't exist in database, searching it in the local machine.
> 2017-01-03T00:44:56.936643+00:00 app[bot.1]: [STEAM] Sentry file doesn't exist in the local machine.
> 2017-01-03T00:44:59.014178+00:00 app[bot.1]: [STEAM] Connected to Steam
> 2017-01-03T00:44:59.336871+00:00 app[bot.1]: [STEAM] Successfully logged in!
> 2017-01-03T00:45:05.699511+00:00 app[bot.1]: [DOTA] Running!
> 2017-01-03T00:45:05.849796+00:00 app[bot.1]: Error: Incorrect login details were provided.
> 2017-01-03T00:45:05.849799+00:00 app[bot.1]:     at WebSocketManager.client.ws.once.event (/app/node_modules/discord.js/src/client/ClientManager.js:36:41)
> 2017-01-03T00:45:05.849800+00:00 app[bot.1]:     at WebSocketManager.g (events.js:286:16)
> 2017-01-03T00:45:05.849800+00:00 app[bot.1]:     at emitOne (events.js:96:13)
> 2017-01-03T00:45:05.849801+00:00 app[bot.1]:     at WebSocketManager.emit (events.js:188:7)
> 2017-01-03T00:45:05.849802+00:00 app[bot.1]:     at WebSocketManager.eventClose (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:195:10)
> 2017-01-03T00:45:05.849803+00:00 app[bot.1]:     at WebSocket.ws.onclose (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:82:35)
> 2017-01-03T00:45:05.849806+00:00 app[bot.1]:     at WebSocket.onClose (/app/node_modules/ws/lib/WebSocket.js:446:14)
> 2017-01-03T00:45:05.849806+00:00 app[bot.1]:     at emitTwo (events.js:106:13)
> 2017-01-03T00:45:05.849807+00:00 app[bot.1]:     at WebSocket.emit (events.js:191:7)
> 2017-01-03T00:45:05.849808+00:00 app[bot.1]:     at WebSocket.cleanupWebsocketResources (/app/node_modules/ws/lib/WebSocket.js:950:8)
> 2017-01-03T00:45:05.849809+00:00 app[bot.1]:     at emitNone (events.js:91:20)
> 2017-01-03T00:45:05.849810+00:00 app[bot.1]:     at TLSSocket.emit (events.js:185:7)
> 2017-01-03T00:45:05.849811+00:00 app[bot.1]:     at endReadableNT (_stream_readable.js:975:12)
> 2017-01-03T00:45:05.849811+00:00 app[bot.1]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
> 2017-01-03T00:45:05.849812+00:00 app[bot.1]:     at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by bippum** [comment]
You'll need to create an empty file called `sentry` in the directory the bot runs in. https://github.com/Arcana/node-dota2/blob/staging/examples/config.js.example

**Comment by MeLlamoPablo** [comment]
@bippum not really, it looks like the issue is being caused by Discord.js and not by node-dota2, as the bot is able to log in to Steam (`[STEAM] Successfully logged in!`, `[DOTA] Running!`).

@mcarmody I assume you have got your Discord Bot token and used the `npm run setup` script to send it to the database, right?

**Comment by mcarmody** [comment]
Yep, let me go try and redo that whole process and see what I come up with.  I wasn't sure what the failed login was *for*, so it helps to know that it's Discord related.

**Comment by mcarmody** [comment]
Where should I be entering the bot credentials during the setup process?

**Comment by MeLlamoPablo** [comment]
The setup process should look like this:

```
PS C:\Users\Pablo\NodeProjects\schedulebot> npm run setup

> schedulebot@1.0.6 setup C:\Users\Pablo\NodeProjects\schedulebot
> node ./setup.js

Hello! Welcome to the ScheduleBot setup script.
This script will create your database structure to get ScheduleBot working.
First, let's connect to your postgres database. Enter your db info:

? Host localhost
? Database schedulebot
? User postgres
? Password ********
? Use SSL? No

Awesome! We can begin with the creation of the structure.

? Do you want to procceed? Yes

Alright, database schema created!
Now we just need your bot's token.
For security reasons, this is not stored on your config.js file; it's stored on the database.

You can get your bot's token at the following address:
https://discordapp.com/developers/applications/me

? Your bot's token YOUR BOT TOKEN GOES HERE

Just one more thing:
We need to set up the bot's admin. More people can be added later,
but we need at least one right now so the bot can be used.

Please, enter the admin's discord's user ID
To get that, go to Discord's user settings, then appearance, then check "Developer Mode".
After that, right click on your username, and click "Copy ID"

? Admin's discord user ID YOUR DISCORD USER ID GOES HERE
? Admin's discord user name (used to label the database entry) YOUR DISCORD USERNAME GOES HERE

That's it! We're done!
You can run ScheduleBot with npm run bot

Have fun!
```

This is from the "Local Installation", but the only difference from the Heroku Deployment is that you have to supply the database credentials that are provided by Heroku, and have to set `Use SSL?` to yes. Other than that, it should be the same.

**Comment by mcarmody** [comment]
Well I have no idea what I did differently, but I cleared the Heroku DB and re-ran all the setup commands and it's worked this time!  Thanks for the help... I guess I must have typed something wrong, somewhere in the process.

**Comment by MeLlamoPablo** [comment]
No worries, man! By the looks of it, you probably mistyped the token.
