### ISSUE TITLE
Possible bug - invisible lobby

### ISSUE THREAD

**Issue by Shurugaz** [MeLlamoPablo/schedulebot#8]
using v1.0.6:
I made an event with the create command and added inhouse (8 hours before the event would take place).
Didn't get a normal lobby invite from the bot, used resend-invite and joined the lobby. The lobby was invisible though. In dota I could click 'back to lobby', but nothing happened. I couldnt join any other lobby or start matchmaking after that, I had to use 'force_leave_game_button 1' in the dota 2 console. Could this be because the event was created 8 hours early?

**Comment by MeLlamoPablo** [comment]
That shouldn't be the reason, the lobby should only be created on the specified time. Do you have the console logs for the time when that hapoened?

**Comment by Shurugaz** [comment]
unfortunately not. We're testing it again tonight with the same setup

**Comment by Shurugaz** [comment]
I reinstalled everything, the issue seems to be solved.

**Comment by MeLlamoPablo** [comment]
Good to know. Reopen the issue if you detect the problem again.
