### ISSUE TITLE
Kick command kicks the admin

### ISSUE THREAD

**Issue by Shurugaz** [MeLlamoPablo/schedulebot#9]
Kick command kicks the admin, not the player mentioned

**Comment by MeLlamoPablo** [comment]
Thanks for reporting. Both are caused by lazy testing on my side, so I apologize. I'll get on it asap.

**Comment by Shurugaz** [comment]
No problem at all, we all know it's still a work in progress :)

**Comment by MeLlamoPablo** [comment]
Fixed in version 1.1.1. You may update your bot by following the instructions [here](https://github.com/MeLlamoPablo/schedulebot/tree/dota#updating).
